//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThikanaClassifieds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classifieds_Items
    {
        public Classifieds_Items()
        {
            this.Classifieds_Item_Image = new HashSet<Classifieds_Item_Image>();
        }
    
        public int Classifieds_Item_Id { get; set; }
        public int Classifieds_Category_Id { get; set; }
        public string Classifieds_Item_Title { get; set; }
        public string Classifieds_Item_Location { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Classifieds_Item_Price { get; set; }
        public string Its_Premium { get; set; }
        public string Classifieds_Item_Description { get; set; }
        public string Classifieds_Item_Phone { get; set; }
    
        public virtual Classifieds_Category Classifieds_Category { get; set; }
        public virtual ICollection<Classifieds_Item_Image> Classifieds_Item_Image { get; set; }
    }
}
