//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThikanaClassifieds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classifieds_ads
    {
        public int Classifieds_ads_Id { get; set; }
        public string Classifieds_ads_Title { get; set; }
        public string Classifieds_ads_Link { get; set; }
        public string Classifieds_ads_Image { get; set; }
    }
}
