//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThikanaClassifieds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classifieds_Category
    {
        public Classifieds_Category()
        {
            this.Classifieds_Items = new HashSet<Classifieds_Items>();
        }
    
        public int Classifieds_Category_Id { get; set; }
        public string Classifieds_Category_Name { get; set; }
        public string Classifieds_Category_Image { get; set; }
    
        public virtual ICollection<Classifieds_Items> Classifieds_Items { get; set; }
    }
}
